const feedbackMarkup="\n<button id=\"feedback-launch\" type=\"button\" aria-label=\"Give feedback\" aria-haspopup=\"dialog\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" aria-hidden=\"true\"><path d=\"M5 4h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H9l-6 3V6a2 2 0 0 1 2-2Z\"/><path d=\"M7 9h10M7 13h7\"/></svg><span class=\"feedback-label\">Give feedback</span></button>\n<dialog id=\"feedback-panel\" aria-labelledby=\"feedback-title\">\n<button id=\"feedback-close\" type=\"button\" aria-label=\"Close feedback\" style=\"position:absolute;right:12px;top:12px;border:0;padding:5px;font-size:25px;background:transparent\">\u00d7</button><section id=\"feedback-compose\"><h2 id=\"feedback-title\" style=\"padding-right:28px\">Send Graham your feedback</h2><p id=\"feedback-stage\" hidden></p>\n<form id=\"feedback-form\"><label for=\"feedback-message\" style=\"position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0\">Your feedback</label><textarea id=\"feedback-message\" maxlength=\"5000\" required placeholder=\"Tell Graham what doesn't work for you in the research experience or questions\u2026\"></textarea><p id=\"feedback-error\" role=\"alert\"></p><div id=\"feedback-actions\" style=\"justify-content:flex-end\"><button id=\"feedback-send\" type=\"submit\">Send</button></div></form>\n<p style=\"font-size:13px\">Preview only: nothing is sent. Comments stay in this tab's memory.</p></section>\n<section id=\"feedback-success\" hidden aria-labelledby=\"feedback-success-title\"><div id=\"feedback-success-mark\" aria-hidden=\"true\">\u2713</div><h2 id=\"feedback-success-title\" tabindex=\"-1\">Thank you</h2><p id=\"feedback-receipt\" role=\"status\" aria-live=\"polite\"></p><button id=\"feedback-done\" type=\"button\">Done</button></section>\n</dialog>\n";document.body.insertAdjacentHTML('beforeend',feedbackMarkup);

(()=>{const launch=document.querySelector('#feedback-launch'),panel=document.querySelector('#feedback-panel'),message=document.querySelector('#feedback-message'),receipt=document.querySelector('#feedback-receipt'),compose=document.querySelector('#feedback-compose'),success=document.querySelector('#feedback-success'),send=document.querySelector('#feedback-send'),error=document.querySelector('#feedback-error');const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const preview=window.__FEEDBACK_PREVIEW__===true;const submissions=[];if(preview)window.feedbackPreview={submissions};let submissionId=null,metadata=null,openedY=0,timer=null,confirmed=false,busy=false;
if(new URLSearchParams(location.search).get('placement')!=='tab'){document.body.classList.add('feedback-pill');launch.querySelector('.feedback-label').textContent='Feedback'}
if(preview){const banner=document.createElement('div');banner.id='feedback-demo-banner';banner.textContent='Local feedback preview · nothing is sent. Compare: ';const link=document.createElement('a');link.href=location.pathname+(document.body.classList.contains('feedback-pill')?'':'?placement=pill');link.textContent=document.body.classList.contains('feedback-pill')?'Side tab':'Feedback pill';link.style.color='#ffad77';banner.append(link);document.body.prepend(banner);
}if(!preview)compose.querySelector('p:last-child').remove();launch.onclick=()=>{clearTimeout(timer);openedY=scrollY;confirmed=false;busy=false;compose.hidden=false;success.hidden=true;panel.setAttribute('aria-labelledby','feedback-title');send.disabled=false;error.textContent='';const screen=document.querySelector('.screen.active'),visible=[...document.querySelectorAll('.pair-item')].filter(r=>!r.hidden);metadata={stage:screen?.id||'unknown',statementIndices:visible.map(r=>Number(r.dataset.statementIndex)),instrumentVersion:'phase3-v4-2026-09-13-paired',channel:'web-preview'};document.querySelector('#feedback-stage').textContent=metadata.stage==='screen-pairs'?'About this question pair':'About this part of the experience';submissionId ||= crypto.randomUUID();const origin=launch.getBoundingClientRect();panel.showModal();const target=panel.getBoundingClientRect();launch.classList.add('away');if(!reduced())panel.animate([{opacity:0,transform:`translate(${origin.x+origin.width/2-target.x-target.width/2}px,${origin.y+origin.height/2-target.y-target.height/2}px) scale(.12)`},{opacity:1,transform:'translate(0,0) scale(1)'}],{duration:320,easing:'cubic-bezier(.2,.8,.2,1)'});message.focus();};
const close=()=>{clearTimeout(timer);panel.close()};document.querySelector('#feedback-close').onclick=close;document.querySelector('#feedback-done').onclick=close;
panel.addEventListener('close',()=>{clearTimeout(timer);launch.classList.remove('away');if(confirmed){message.value='';submissionId=null;window.feedbackSubmissionTime=null}busy=false;launch.focus({preventScroll:true});window.scrollTo(0,openedY)});
message.oninput=()=>message.setCustomValidity('');
const deliver=async()=>{if(!panel.open)return;if(!reduced()){const anim=panel.animate([{opacity:1,transform:'translate(0,0) scale(1)'},{opacity:0,transform:'translate(65vw,-65vh) scale(.1)'}],{duration:420,easing:'cubic-bezier(.45,0,.8,.4)'});await anim.finished.catch(()=>{})}if(panel.open)close()};
document.querySelector('#feedback-form').onsubmit=async e=>{e.preventDefault();if(busy)return;if(!message.value.trim()){message.setCustomValidity('Please enter your feedback.');message.reportValidity();return}busy=true;send.disabled=true;error.textContent='';let row=submissions.find(s=>s.id===submissionId);if(!row){row={id:submissionId,text:message.value,metadata};submissions.push(row)}if(!preview){try{const response=await fetch('/api/research-invite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'feedback-submission',submissionId,feedback:message.value,stage:metadata.stage,statementIndices:metadata.statementIndices,instrumentVersion:metadata.instrumentVersion,submittedAt:window.feedbackSubmissionTime||(window.feedbackSubmissionTime=new Date().toISOString())})});const result=await response.json();if(!response.ok||result.saved!==true)throw Error(result.error||'Could not save your feedback. Please retry.');}catch(e){error.textContent=e.message;busy=false;send.disabled=false;return}}confirmed=true;compose.hidden=true;success.hidden=false;panel.setAttribute('aria-labelledby','feedback-success-title');receipt.textContent=preview?'Saved in this preview only.':'Your feedback has been received.';document.querySelector('#feedback-success-title').focus();timer=setTimeout(deliver,1600)};
})();
