import assert from 'node:assert/strict';import{readFileSync}from'node:fs';const {default:save,prepareSubmission}=await import('data:text/javascript;base64,'+Buffer.from(readFileSync(new URL('../lib/research-feedback-submission.js',import.meta.url),'utf8')).toString('base64'));
const data={submissionId:'71890dda-2c5d-486b-8925-282ba29d62ba',feedback:'Synthetic: button overlaps; questions confusing.',stage:'screen-pairs',statementIndices:[0,1],instrumentVersion:'phase3-v4-2026-09-13-paired',submittedAt:new Date().toISOString()};
const p=prepareSubmission(data);assert.equal(prepareSubmission(data).id,p.id);assert.equal(prepareSubmission({...data,statementIndices:[1,0]}).id,p.id);assert.notEqual(prepareSubmission({...data,feedback:'Edited fictional feedback'}).id,p.id);assert.equal(Object.values(p.fields).includes(data.feedback),true);assert.equal(JSON.stringify(p.fields).includes('answers'),false);assert.throws(()=>prepareSubmission({...data,feedback:' '.repeat(3)}));assert.throws(()=>prepareSubmission({...data,feedback:'a'.repeat(5001)}));assert.throws(()=>prepareSubmission({...data,statementIndices:[24]}));
const original=global.fetch;const env={...process.env};const respond=()=>({setHeader(){},status(code){this.code=code;return this},json(body){this.body=body;return this}});let writes=0,calls=0;
try{delete process.env.RESEARCH_FEEDBACK_CAPTURE_ENABLED;let r=respond();await save({method:'POST',headers:{}},r,data);assert.equal(r.code,503);process.env.RESEARCH_FEEDBACK_CAPTURE_ENABLED='true';process.env.AIRTABLE_RESEARCH_TOKEN='synthetic-test-token';global.fetch=async(url,options)=>{calls++;if(options.method==='PATCH'){writes++;const b=JSON.parse(options.body);assert.deepEqual(b.performUpsert.fieldsToMergeOn,['fldODy3mOhqL995KL']);assert.equal(JSON.stringify(b).includes('Triage status'),false);return{ok:true,json:async()=>({records:[{fields:b.records[0].fields}]})}}return{ok:true,json:async()=>({records:writes?[{id:'synthetic-source'}]:[]})}};
r=respond();await save({method:'POST',headers:{}},r,data);assert.equal(r.code,201);assert.equal(r.body.saved,true);r=respond();await save({method:'POST',headers:{}},r,data);assert.equal(r.code,200);assert.equal(writes,1);const oldCalls=calls;r=respond();await save({method:'POST',headers:{origin:'https://unrelated.invalid',host:'example.invalid'}},r,data);assert.equal(r.code,403);assert.equal(calls,oldCalls);
global.fetch=async()=>({ok:false});r=respond();await save({method:'POST',headers:{}},r,data);assert.equal(r.code,502);assert.equal(r.body.saved,undefined);
}finally{global.fetch=original;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env)}
console.log('Passed source capture validation, stable receipt, safe fields, retry without duplicate write, fail-closed activation/origin and upstream failure. Fetches mocked; no participant data or emails.');
